spring.application.name=apilimiter


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/sp
spring.datasource.username=root
spring.datasource.password=bb2bfmicyu

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security config
spring.security.user.name=harsh
spring.security.user.password=pass


jwt.secretkey=jcnkjscjidcjkn2893d2uc2b9cenjdewinceuwf2938b2feufbf982bebffb0232obf92b92fb9wf82b9fo29fu92fbwoeuwi